export default {
  name: 'featureReview',
  title: 'Feature Review',
  type: 'document',
  fields: [
    { name: 'title', type: 'string', title: 'Movie Title' },
    { name: 'id', type: 'string', title: 'Review ID' },
    { name: 'isFeatured', type: 'boolean', title: 'Is Main Feature?', initialValue: false },
    { name: 'slug', type: 'slug', title: 'URL Slug', options: { source: 'title' } },
    { name: 'director', type: 'string', title: 'Director' },
    { name: 'year', type: 'string', title: 'Release Year' },
    { name: 'ratingStars', type: 'string', title: 'Rating' },
    { name: 'publishedDate', type: 'string', title: 'Display Date' },
    { name: 'heroImage', type: 'url', title: 'Hero Image URL' },
    { name: 'verdict', type: 'string', title: 'The Verdict' },
    { name: 'paragraphs', type: 'array', title: 'Review Paragraphs', of: [{type: 'text'}] },
    { name: 'quotes', type: 'array', title: 'Pull Quotes', of: [{type: 'string'}] },
    { name: 'stills', type: 'array', title: 'Film Stills', of: [{type: 'url'}] },
    { name: 'footerText', type: 'string', title: 'Availability Footer' },
    { name: 'footerLink', type: 'url', title: 'Call to Action Link' },
  ],
}